on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
        gradle: [ '7.3.3', '7.4.2', '7.5.1', '7.6', '8.0-rc-1' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build on Java ${{ matrix.java }}
        uses: burrunan/gradle-cache-action@v1
        env:
          TEST_GRADLE_VERSION: ${{ matrix.gradle }}
        with:
          arguments: build


