on: workflow_call

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
        gradle: [ '7.3.3', '7.4.2', '7.5.1', '7.6.3', '8.0.1', '8.1.1', '8.2.1', '8.3', '8.4', '8.5', '8.6' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build on Java ${{ matrix.java }}
        run: ./gradlew build
        env:
          TEST_GRADLE_VERSION: ${{ matrix.gradle }}

  results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build Outcome
    needs: [ build ]
    steps:
      - run: |
          result="${{ needs.build.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi


