name: CI
concurrency: ci

on:
  push:
    branches-ignore: ["master"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build using Java ${{ matrix.java }}
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build


